# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    backendType: 'azurerm'
    backendServiceArm: 'azure_visual_studio_subscription'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'rg-terrafom-pipelines'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'saterraform413'
    backendAzureRmStorageAccountSku: 'Standard_LRS'
    backendAzureRmContainerName: 'az300demo'
    backendAzureRmKey: 'foo'
    allowTelemetryCollection: true


- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    environmentServiceName: 'azure_visual_studio_subscription'
    allowTelemetryCollection: true
    publishPlanResults: 'plan'

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    environmentServiceName: 'azure_visual_studio_subscription'
    commandOptions: '--auto-approve'
    allowTelemetryCollection: true