# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: terraformStorageAccount
    displayName: "Storage account name for terraform backend"
    type: string
    default: 'saterraform413'

  - name: terraformResourceGroup
    displayName: "Resource group name for terraform backend"
    type: string
    default: 'rg-terrafom-pipelines'

  - name: terraformStorageContainer
    displayName: "Storage container name for terraform backend"
    type: string
    default: 'az300wdemo'

  - name: terraformStateFile
    displayName: "State file name for terraform backend"
    type: string
    default: 'test.tfstate'

steps:
- task: AzureCLI@2
  displayName: 'Ensure infrastructure for terraform backend'
  inputs:
    azureSubscription: 'azure_visual_studio_subscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      az storage account create \
        --name ${{ parameters.terraformStorageAccount }}\
        --resource-group ${{ parameters.terraformResourceGroup }}\
        --kind StorageV2 \
        --sku Standard_LRS \
        --https-only true \
        --allow-blob-public-access false

      az storage container create \
        --name ${{ parameters.terraformStorageContainer }} \
        --account-name ${{ parameters.terraformStorageAccount }} \
        --auth login

- task: AzureCLI@2
  displayName: "terraform init with azurerm backend"
  inputs:
    azureSubscription: 'azure_visual_studio_subscription'
    scriptType: 'bash'
    addSpnToEnvironment: true
    scriptLocation: 'inlineScript'
    inlineScript: |

      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_CLIENT_SECRET=$servicePrincipalKey
      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
      export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)

      terraform init \
        -backend-config="storage_account_name=${{ parameters.terraformStorageAccount }}" \
        -backend-config="container_name=${{ parameters.terraformStorageContainer }}" \
        -backend-config="key=${{ parameters.terraformStateFile }}" \
        -backend-config="resource_group_name=${{ parameters.terraformResourceGroup }}"

    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'

- task: AzureCLI@2
  displayName: "terraform apply"
  inputs:
    azureSubscription: 'azure_visual_studio_subscription'
    scriptType: 'bash'
    addSpnToEnvironment: true
    scriptLocation: 'inlineScript'
    inlineScript: |

      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_CLIENT_SECRET=$servicePrincipalKey
      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
      export ARM_TENANT_ID=$(az account show --query tenantId -o tsv)

      terraform apply -auto-approve

    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'